spring:
  datasource:
    # h2-db-file-name: local ? h2 db ?? (???.mv.db)
    url: jdbc:h2:tcp://localhost/~/data/h2/workspaces/testcode
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace