### 카오스멍키 에러 응답 설정
POST http://localhost:8080/actuator/chaosmonkey/assaults
Content-Type: application/json

{
  "level": 3,
  "latencyActive": false,
  "exceptionsActive": true,
  "exception": {
    "type": "java.lang.RuntimeException"
  }
}
